### ISSUE TITLE
I have a question about epipolar affinity

### ISSUE THREAD

**Issue by lim8540** [ivclab/Part-Aware_Measurement_for_3D_Pose_Estimation_and_Tracking#3]
Can you explain the difference between epipolar_affinity and epipolar_affinity_parallel in matching.py

**Comment by B10532021** [comment]
Well, they're basically the same thing, the only difference is that one was done by for loop, and the one with "parallel" was done with numpy. Sorry for the ambiguatiy.

**Comment by lim8540** [comment]
Thank you for your reply. is parallel much faster than normal?

**Comment by B10532021** [comment]
That's right it sure did.

**Comment by lim8540** [comment]
OK! Thanks :)
