### ISSUE TITLE
Is there a reason that did not use kalman filter?

### ISSUE THREAD

**Issue by lim8540** [ivclab/Part-Aware_Measurement_for_3D_Pose_Estimation_and_Tracking#4]
I find that Kalman filter is in the code but, you did not use them.

Can I know WHY?

Is there a problem in algorithms itself? or kalman filter results in bad accuracy?

Thank you for your work!

**Comment by B10532021** [comment]
Well, there is no problem with the algorithm. We just found out that Kalman Filter, which we didn't pay too much work on it, won't significantly affect the result during our testing process while One Euro Filter can also reach good performance. I believe that Kalman Filter can benefit the results if you can research more thoroughly on it.

**Comment by lim8540** [comment]
Thank you for your reply!
Do you recommend use one Euro filter instead of Gaussian filter?
or Are you using two filters together?

**Comment by B10532021** [comment]
Sorry, I'm gonna leave the answer to you, since I can't promise the result while I didn't dig into the comparison between these two filters. However, I could tell that we are satisfied with the result of the One Euro Filter so far.

**Comment by lim8540** [comment]
Oh, Ok! I really appreciate your work and reply. Thanks :)
